version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8381:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User Id=supabase_admin;Password=Sup3rAdminDB;Server=supabase-db;Port=5432;Database=postgres;
      - TZ="America/Sao_Paulo"
      - LANG=pt_BR.UTF-8
    networks:
      - supabase_default

networks:
  supabase_default:
    external: true